version: '3.8'

services:
  ai:
    image: saivardhan53/airepo:latest
    ports:
      - "80:80"
    volumes:
      - aivolume:/app
    deploy:
      replicas: 3

  ml:
    image: saivardhan53/mlrepo:latest
    ports:
      - "81:80"
    volumes:
      - mlvolume:/app
    deploy:
      replicas: 3

  ds:
    image: saivardhan53/dsrepo:latest
    ports:
      - "82:80"
    volumes:
      - dsvolume:/app
    deploy:
      replicas: 3

  it:
    image: saivardhan53/itrepo:latest
    ports:
      - "83:80"
    volumes:
      - itvolume:/app
    deploy:
      replicas: 3

volumes:
  aivolume:
  mlvolume:
  dsvolume:
  itvolume:
